export {};

function compile(gl:WebGL2RenderingContext,type:number,source:string):WebGLShader{const s=gl.createShader(type);if(!s)throw new Error("createShader failed");gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const log=gl.getShaderInfoLog(s)??"compile failed";gl.deleteShader(s);throw new Error(log);}return s;}
function makeProgram(gl:WebGL2RenderingContext):WebGLProgram{const vs=compile(gl,gl.VERTEX_SHADER,`#version 300 es
layout(location=0)in vec2 position;layout(location=1)in vec2 offset;void main(){gl_Position=vec4(position+offset,0,1);}`),fs=compile(gl,gl.FRAGMENT_SHADER,`#version 300 es
precision highp float;out vec4 color;void main(){color=vec4(.9,.35,.2,1);}`),p=gl.createProgram();if(!p){gl.deleteShader(vs);gl.deleteShader(fs);throw new Error("createProgram failed");}gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(p,gl.LINK_STATUS)){const log=gl.getProgramInfoLog(p)??"link failed";gl.deleteProgram(p);throw new Error(log);}return p;}
const canvas=document.body.appendChild(document.createElement("canvas"));canvas.width=640;canvas.height=360;const gl=canvas.getContext("webgl2");if(!gl)throw new Error("WebGL 2 unavailable");const p=makeProgram(gl),vao=gl.createVertexArray(),vertices=gl.createBuffer(),instances=gl.createBuffer();if(!vao||!vertices||!instances)throw new Error("resource allocation failed");
gl.bindVertexArray(vao);gl.bindBuffer(gl.ARRAY_BUFFER,vertices);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([0,.08,-.06,-.06,.06,-.06]),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,2,gl.FLOAT,false,0,0);
const offsets=new Float32Array(200);for(let i=0;i<100;i++){offsets[i*2]=(i%10)*.18-.81;offsets[i*2+1]=Math.floor(i/10)*.18-.81;}gl.bindBuffer(gl.ARRAY_BUFFER,instances);gl.bufferData(gl.ARRAY_BUFFER,offsets,gl.STATIC_DRAW);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,2,gl.FLOAT,false,0,0);gl.vertexAttribDivisor(1,1);
gl.useProgram(p);gl.viewport(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight);gl.drawArraysInstanced(gl.TRIANGLES,0,3,100);gl.bindVertexArray(null);gl.useProgram(null);gl.deleteBuffer(vertices);gl.deleteBuffer(instances);gl.deleteVertexArray(vao);gl.deleteProgram(p);
