export {};

function build(gl: WebGL2RenderingContext, type: number, source: string): WebGLShader { const s=gl.createShader(type); if(!s)throw new Error("shader allocation failed"); gl.shaderSource(s,source); gl.compileShader(s); if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const log=gl.getShaderInfoLog(s)??"compile failed";gl.deleteShader(s);throw new Error(log);} return s; }
function link(gl: WebGL2RenderingContext, vsSource:string, fsSource:string):WebGLProgram { const vs=build(gl,gl.VERTEX_SHADER,vsSource),fs=build(gl,gl.FRAGMENT_SHADER,fsSource),p=gl.createProgram();if(!p){gl.deleteShader(vs);gl.deleteShader(fs);throw new Error("program allocation failed");}gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(p,gl.LINK_STATUS)){const log=gl.getProgramInfoLog(p)??"link failed";gl.deleteProgram(p);throw new Error(log);}return p;}
const canvas=document.body.appendChild(document.createElement("canvas"));canvas.width=512;canvas.height=512;const gl=canvas.getContext("webgl2");if(!gl)throw new Error("WebGL 2 unavailable");
const p=link(gl,`#version 300 es
const vec2 pos[6]=vec2[6](vec2(-1,-1),vec2(1,-1),vec2(-1,1),vec2(-1,1),vec2(1,-1),vec2(1,1));out vec2 uv;void main(){gl_Position=vec4(pos[gl_VertexID],0,1);uv=pos[gl_VertexID]*vec2(.5,-.5)+.5;}`,`#version 300 es
precision highp float;in vec2 uv;uniform sampler2D image;out vec4 color;void main(){color=texture(image,uv);}`);
const texture=gl.createTexture();if(!texture)throw new Error("texture allocation failed");gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_ALIGNMENT,1);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,2,2,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([255,0,0,255,0,255,0,255,0,0,255,255,255,255,0,255]));gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);
const vao=gl.createVertexArray();if(!vao)throw new Error("VAO allocation failed");gl.bindVertexArray(vao);gl.useProgram(p);const location=gl.getUniformLocation(p,"image");if(location===null)throw new Error("image uniform missing");gl.uniform1i(location,0);gl.viewport(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight);gl.drawArrays(gl.TRIANGLES,0,6);
gl.bindTexture(gl.TEXTURE_2D,null);gl.bindVertexArray(null);gl.useProgram(null);gl.deleteTexture(texture);gl.deleteVertexArray(vao);gl.deleteProgram(p);
